# Generated by Django 5.2.4 on 2026-07-17 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # SeparateDatabaseAndState : yeki_passwordresetotp / yeki_profile
    # existent déjà (créées par yeki.0001_initial) — état uniquement.
    operations = [
      migrations.SeparateDatabaseAndState(
        state_operations=[
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP Réinitialisation',
                'db_table': 'yeki_passwordresetotp',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(blank=True, choices=[('admin', 'Administrateur'), ('enseignant_admin', 'Enseignant Administrateur'), ('enseignant_cadre', 'Enseignant Cadre'), ('enseignant_principal', 'Enseignant Principal'), ('enseignant', 'Enseignant'), ('apprenant', 'Apprenant')], default='Apprenant', max_length=20, null=True)),
                ('cursus', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_cursus', models.CharField(blank=True, max_length=100, null=True)),
                ('niveau', models.CharField(blank=True, max_length=100, null=True)),
                ('filiere', models.CharField(blank=True, max_length=100, null=True)),
                ('licence', models.CharField(blank=True, max_length=100, null=True)),
                ('ville', models.CharField(blank=True, help_text='Ville de résidence', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('whatsapp', models.CharField(blank=True, help_text='Numéro WhatsApp pour les répétiteurs', max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'yeki_profile',
            },
        ),
        ],
        database_operations=[],
      ),
    ]
