# Generated by Django 5.2.4 on 2026-07-17 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('formation', '0001_initial'),
        # accounts.0001 et formation.0001 sont des SeparateDatabaseAndState
        # (état seul, aucun DDL réel — voir leurs commentaires) : les tables
        # physiques `yeki_profile`/`yeki_departement` ne sont réellement
        # créées que par yeki.0001_initial (app monolithe d'origine). Cette
        # migration-ci fait un VRAI ALTER TABLE dessus (AddField/AlterField),
        # donc elle doit explicitement dépendre de la création physique,
        # sinon l'ordre relatif entre 'yeki' et 'accounts'/'formation' n'est
        # pas garanti par le graphe (repéré lors de la mise en place de
        # pytest : une base fraîche construite depuis zéro exposait
        # l'absence de cette dépendance, invisible jusqu'ici car le seul
        # environnement testé — db.sqlite3 — a toujours réutilisé les
        # tables physiques déjà existantes plutôt que d'être reconstruit
        # depuis zéro).
        ('yeki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profils', to='formation.departement'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('admin', 'Administrateur'), ('service_client', 'Service Client'), ('enseignant_admin', 'Enseignant Administrateur'), ('enseignant_cadre', 'Enseignant Cadre'), ('enseignant_principal', 'Enseignant Principal'), ('enseignant', 'Enseignant'), ('apprenant', 'Apprenant')], default='Apprenant', max_length=20, null=True),
        ),
    ]
