# Generated by Django 5.2.4 on 2026-07-17 22:48

import logging

from django.db import migrations, models
from django.db.models import Q

logger = logging.getLogger(__name__)


def normaliser_user_type(apps, schema_editor):
    """
    CONSTAT (P2.1) : default='Apprenant' (majuscule) ne correspondait à
    AUCUNE valeur valide de USER_TYPES (toutes en minuscules) — toute ligne
    créée avec ce défaut, ou avec user_type NULL, doit être corrigée vers
    'apprenant'.
    """
    Profile = apps.get_model('accounts', 'Profile')
    nb = Profile.objects.filter(Q(user_type='Apprenant') | Q(user_type__isnull=True)).update(
        user_type='apprenant'
    )
    logger.info("P2.1 : %s Profile normalisés vers user_type='apprenant'", nb)


def revert_noop(apps, schema_editor):
    # Irréversible par nature (on ne peut pas savoir quelles lignes étaient
    # à l'origine 'Apprenant'/NULL) — no-op volontaire, pas de perte de
    # données au moment du forward donc rien à annuler.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_departement_alter_profile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_repetiteur',
            field=models.BooleanField(default=False, help_text='Validé par le Service Client. Ne concerne que les enseignants.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('admin', 'Administrateur'), ('service_client', 'Service Client'), ('enseignant_admin', 'Enseignant Administrateur'), ('enseignant_cadre', 'Enseignant Cadre'), ('enseignant_principal', 'Enseignant Principal'), ('enseignant', 'Enseignant'), ('apprenant', 'Apprenant')], db_index=True, default='apprenant', max_length=20, null=True),
        ),
        migrations.RunPython(normaliser_user_type, revert_noop),
    ]
