# Generated by Django 5.2.4 on 2026-08-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile_is_repetiteur_alter_profile_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="date_naissance",
            field=models.DateField(blank=True, null=True),
        ),
    ]
