# Generated by Django 5.2.4 on 2026-07-17 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('formation', '0001_initial'),
    ]

    # SeparateDatabaseAndState : la table existe déjà (créée par
    # yeki.0001_initial) — état uniquement, aucune opération réelle.
    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Repetiteur',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('ville', models.CharField(max_length=100)),
                        ('telephone', models.CharField(help_text='Format international recommandé, ex: 2376XXXXXXXX', max_length=20)),
                        ('disponible', models.BooleanField(default=True)),
                        ('tarif_mensuel', models.PositiveIntegerField(default=7500, help_text='Tarif mensuel en FCFA')),
                        ('note_moyenne', models.FloatField(default=0.0)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repetiteurs', to='formation.cours')),
                        ('enseignant', models.ForeignKey(limit_choices_to={'user_type__in': ['enseignant', 'enseignant_secondaire']}, on_delete=django.db.models.deletion.CASCADE, related_name='fiches_repetiteur', to='accounts.profile')),
                    ],
                    options={
                        'verbose_name': 'Répétiteur',
                        'db_table': 'yeki_repetiteur',
                        'ordering': ['-disponible', 'ville'],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
