# Generated by Django 5.2.4 on 2026-07-17 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_is_repetiteur_alter_profile_user_type'),
        ('repetiteurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repetiteur',
            name='enseignant',
            field=models.ForeignKey(limit_choices_to={'is_repetiteur': True, 'user_type': 'enseignant'}, on_delete=django.db.models.deletion.CASCADE, related_name='fiches_repetiteur', to='accounts.profile'),
        ),
    ]
