# Generated by Django 5.2.4 on 2026-07-18 01:45

import apps.repetiteurs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repetiteurs', '0002_alter_repetiteur_enseignant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repetiteur',
            name='tarif_mensuel',
            field=models.PositiveIntegerField(default=apps.repetiteurs.models._tarif_repetiteur_defaut, help_text='Tarif mensuel en FCFA'),
        ),
    ]
