# Generated by Django 5.2.4 on 2026-07-17 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # SeparateDatabaseAndState : les 7 tables existent déjà (créées par
    # yeki.0001_initial) — état uniquement, aucune opération réelle.
    operations = [
      migrations.SeparateDatabaseAndState(
        state_operations=[
        migrations.CreateModel(
            name='YekiCompteIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_commissions', models.PositiveIntegerField(default=0)),
                ('nb_requetes_ia', models.PositiveIntegerField(default=0)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Compte Central Yéki IA',
                'db_table': 'yeki_yekicompteia',
            },
        ),
        migrations.CreateModel(
            name='CinetPayTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('success', 'Succès'), ('failed', 'Échec')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('mtn_momo', 'MTN Mobile Money'), ('orange_money', 'Orange Money'), ('card', 'Carte bancaire')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cinetpay_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'yeki_cinetpaytransaction',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_paiement', models.CharField(choices=[('abonnement_mensuel', 'Abonnement mensuel cursus'), ('abonnement_annuel', 'Abonnement annuel cursus'), ('acces_departement', 'Accès département (concours/formation)'), ('olympiade', 'Participation olympiade'), ('olympiade_participation', 'Participation apprenant à une olympiade')], max_length=25)),
                ('moyen', models.CharField(choices=[('mtn_momo', 'MTN Mobile Money'), ('orange_om', 'Orange Money'), ('carte', 'Carte bancaire'), ('wallet', 'Portefeuille Yeki'), ('cinetpay', 'CinetPay')], max_length=15)),
                ('montant', models.PositiveIntegerField(help_text='Montant en FCFA')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('succes', 'Succès'), ('echec', 'Échec'), ('rembourse', 'Remboursé')], default='en_attente', max_length=15)),
                ('reference', models.CharField(blank=True, max_length=100, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.CharField(blank=True, help_text='ID transaction opérateur', max_length=200)),
                ('commission_yeki', models.PositiveIntegerField(default=0, help_text='Part Yeki en FCFA')),
                ('olympiade_liee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_globaux', to='evaluation.olympiade')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement',
                'db_table': 'yeki_paiement',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AbonnementPremium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_abonnement', models.CharField(choices=[('mensuel', 'Mensuel – 1 500 FCFA'), ('annuel', 'Annuel – 13 000 FCFA')], max_length=10)),
                ('actif', models.BooleanField(default=True)),
                ('debut', models.DateTimeField(auto_now_add=True)),
                ('fin', models.DateTimeField()),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abonnement', to=settings.AUTH_USER_MODEL)),
                ('paiement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paiement.paiement')),
            ],
            options={
                'verbose_name': 'Abonnement Premium',
                'db_table': 'yeki_abonnementpremium',
                'ordering': ['-debut'],
            },
        ),
        migrations.CreateModel(
            name='YekiWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde', models.PositiveIntegerField(default=0, help_text='Solde en FCFA')),
                ('total_recharge', models.PositiveIntegerField(default=0)),
                ('total_depense', models.PositiveIntegerField(default=0)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portefeuille Yéki',
                'db_table': 'yeki_yekiwallet',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transaction', models.CharField(choices=[('credit', 'Crédit (recharge)'), ('debit', 'Débit (dépense)')], max_length=10)),
                ('montant', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('reference_paiement', models.CharField(blank=True, max_length=100)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='paiement.yekiwallet')),
            ],
            options={
                'verbose_name': 'Transaction Wallet',
                'db_table': 'yeki_wallettransaction',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='PaiementOlympiade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.PositiveIntegerField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('rembourse', 'Remboursé')], default='en_attente', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100, unique=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('paye_le', models.DateTimeField(blank=True, null=True)),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_olympiade', to=settings.AUTH_USER_MODEL)),
                ('olympiade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_participants', to='evaluation.olympiade')),
            ],
            options={
                'verbose_name': 'Paiement Olympiade',
                'verbose_name_plural': 'Paiements Olympiades',
                'db_table': 'yeki_paiementolympiade',
                'ordering': ['-cree_le'],
                'unique_together': {('apprenant', 'olympiade')},
            },
        ),
        ],
        database_operations=[],
      ),
    ]
