# Generated by Django 5.2.4 on 2026-07-18 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_is_repetiteur_alter_profile_user_type'),
        ('formation', '0001_initial'),
        ('paiement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraisOperateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operateur', models.CharField(choices=[('orange_money', 'Orange Money'), ('mtn_momo', 'MTN Mobile Money')], max_length=20)),
                ('tranche_min', models.PositiveIntegerField(help_text='Montant minimum de la tranche, en FCFA')),
                ('tranche_max', models.PositiveIntegerField(help_text='Montant maximum de la tranche, en FCFA')),
                ('frais_fixe', models.PositiveIntegerField(default=0, help_text='Frais fixe en FCFA')),
                ('frais_pourcent', models.FloatField(default=0.0, help_text='Frais en pourcentage du montant')),
            ],
            options={
                'verbose_name': 'Frais opérateur',
                'verbose_name_plural': 'Frais opérateur',
                'db_table': 'yeki_frais_operateur',
                'ordering': ['operateur', 'tranche_min'],
            },
        ),
        migrations.CreateModel(
            name='DemandeRetrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_brut', models.PositiveIntegerField(help_text='Montant demandé, en FCFA')),
                ('frais_operateur', models.PositiveIntegerField(default=0, help_text='Calculé selon la grille FraisOperateur au moment de la demande')),
                ('montant_net', models.PositiveIntegerField(help_text='Montant effectivement envoyé')),
                ('operateur', models.CharField(choices=[('orange_money', 'Orange Money'), ('mtn_momo', 'MTN Mobile Money')], max_length=20)),
                ('numero_destination', models.CharField(help_text='Numéro du bénéficiaire', max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('refusee', 'Refusée'), ('envoyee', 'Envoyée')], db_index=True, default='en_attente', max_length=15)),
                ('motif_refus', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_retrait', to='accounts.profile')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retraits_traites', to='accounts.profile')),
            ],
            options={
                'verbose_name': 'Demande de retrait',
                'db_table': 'yeki_demande_retrait',
            },
        ),
        migrations.CreateModel(
            name='DemandePaiementManuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('abonnement', 'Abonnement Premium'), ('olympiade', 'Participation olympiade'), ('formation', 'Inscription formation'), ('recharge', 'Recharge portefeuille'), ('presentiel', 'Supplément présentiel')], db_index=True, max_length=20)),
                ('objet_id', models.PositiveIntegerField(blank=True, help_text="ID de l'olympiade / formation concernée", null=True)),
                ('montant', models.PositiveIntegerField()),
                ('operateur', models.CharField(choices=[('orange_money', 'Orange Money'), ('mtn_momo', 'MTN Mobile Money')], max_length=20)),
                ('id_transaction', models.CharField(help_text="Saisi par l'apprenant", max_length=100)),
                ('numero_emetteur', models.CharField(blank=True, max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('refusee', 'Refusée')], db_index=True, default='en_attente', max_length=15)),
                ('motif_refus', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_paiement', to='accounts.profile')),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formation.departement')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_traites', to='accounts.profile')),
            ],
            options={
                'verbose_name': 'Demande de paiement manuel',
                'db_table': 'yeki_demande_paiement_manuelle',
                'constraints': [models.UniqueConstraint(fields=('operateur', 'id_transaction'), name='unique_transaction_par_operateur')],
            },
        ),
    ]
