# Generated by Django 5.2.4 on 2026-07-24 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0002_fraisoperateur_demanderetrait_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandepaiementmanuelle',
            name='montant_constate',
            field=models.PositiveIntegerField(blank=True, help_text='Constaté par le Service Client à la validation', null=True),
        ),
        migrations.AddField(
            model_name='demandepaiementmanuelle',
            name='type_abonnement',
            field=models.CharField(blank=True, choices=[('mensuel', 'Mensuel – 1 500 FCFA'), ('annuel', 'Annuel – 13 000 FCFA')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='paiement',
            name='demande_manuelle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_traces', to='paiement.demandepaiementmanuelle'),
        ),
        migrations.AlterField(
            model_name='demandepaiementmanuelle',
            name='montant',
            field=models.PositiveIntegerField(help_text="Montant déclaré par l'apprenant à la soumission"),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='type_paiement',
            field=models.CharField(choices=[('abonnement_mensuel', 'Abonnement mensuel cursus'), ('abonnement_annuel', 'Abonnement annuel cursus'), ('acces_departement', 'Accès département (concours/formation)'), ('olympiade', 'Participation olympiade'), ('olympiade_participation', 'Participation apprenant à une olympiade'), ('recharge_wallet', 'Recharge portefeuille (manuel)'), ('supplement_presentiel', 'Supplément présentiel')], max_length=25),
        ),
    ]
