# Generated by Django 5.2.4 on 2026-07-27 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0002_historiqueprixdepartement'),
        ('paiement', '0003_demandepaiementmanuelle_montant_constate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='formation.departement'),
        ),
    ]
