# Generated by Django 5.2.4 on 2026-08-09 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0005_alter_cours_color_code'),
        ('paiement', '0004_paiement_departement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnementpremium',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abonnements_premium', to='formation.departement'),
        ),
        migrations.AlterField(
            model_name='abonnementpremium',
            name='type_abonnement',
            field=models.CharField(choices=[('mensuel', 'Mensuel'), ('annuel', 'Annuel')], max_length=10),
        ),
        migrations.AlterField(
            model_name='abonnementpremium',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements_premium', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='demandepaiementmanuelle',
            name='type_abonnement',
            field=models.CharField(blank=True, choices=[('mensuel', 'Mensuel'), ('annuel', 'Annuel')], default='', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='abonnementpremium',
            unique_together={('utilisateur', 'departement')},
        ),
    ]
