# Generated by Django 5.2.4 on 2026-07-17 06:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # SeparateDatabaseAndState : les tables yeki_appversion / yeki_historiqueactivite
    # existent déjà (créées par yeki.0001_initial) — on déclare seulement à
    # Django que ces modèles appartiennent maintenant à l'app "core"
    # (state), sans toucher au schéma réel (database_operations=[]).
    operations = [
      migrations.SeparateDatabaseAndState(
        state_operations=[
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('desktop', 'Desktop'), ('ios', 'iOS'), ('web', 'Web')], default='android', help_text='Plateforme cible', max_length=20)),
                ('version_code', models.PositiveIntegerField(help_text='Numéro de version interne (ex: 2, 3, 4...)')),
                ('version_name', models.CharField(help_text='Nom de version (ex: v1.0.3)', max_length=20)),
                ('download_url', models.URLField(help_text='URL de téléchargement (Firebase Storage)')),
                ('changelog', models.TextField(blank=True, help_text='Description des nouveautés')),
                ('min_version_code', models.PositiveIntegerField(default=1, help_text='Version minimale requise')),
                ('force_update', models.BooleanField(default=False, help_text="Si True, oblige l'utilisateur à mettre à jour")),
                ('is_active', models.BooleanField(default=True, help_text='Version active/public')),
                ('file_size', models.PositiveIntegerField(default=0, help_text='Taille du fichier en octets')),
                ('release_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date de publication')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Version de l'application",
                'verbose_name_plural': "Versions de l'application",
                'db_table': 'yeki_appversion',
                'ordering': ['-version_code'],
                'unique_together': {('platform', 'version_code')},
            },
        ),
        migrations.CreateModel(
            name='HistoriqueActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('teacher_activated', 'Enseignant activé'), ('teacher_type_changed', 'Type enseignant modifié'), ('parcours_modified', 'Parcours modifié'), ('course_created', 'Cours créé'), ('course_modified', 'Cours modifié'), ('course_deleted', 'Cours supprimé'), ('teacher_assigned', 'Enseignant principal assigné'), ('teacher_changed', 'Enseignant principal changé'), ('secondary_added', 'Enseignant secondaire ajouté'), ('secondary_removed', 'Enseignant secondaire retiré'), ('module_created', 'Module créé'), ('module_modified', 'Module modifié'), ('module_deleted', 'Module supprimé'), ('lesson_created', 'Leçon créée'), ('lesson_modified', 'Leçon modifiée'), ('lesson_deleted', 'Leçon supprimée'), ('homework_created', 'Devoir créé'), ('homework_modified', 'Devoir modifié'), ('homework_graded', 'Devoir corrigé'), ('exercise_created', 'Exercice créé'), ('question_added', 'Question ajoutée'), ('olympiad_created', 'Olympiade créée'), ('olympiad_closed', 'Olympiade clôturée'), ('ranking_computed', 'Classement calculé'), ('department_created', 'Département créé'), ('cadre_assigned', 'Cadre assigné'), ('submission_graded', 'Soumission corrigée'), ('login', 'Connexion'), ('logout', 'Déconnexion')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('objet_id', models.PositiveIntegerField(blank=True, null=True)),
                ('objet_type', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_activites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Historique des activités',
                'db_table': 'yeki_historiqueactivite',
                'ordering': ['-timestamp'],
            },
        ),
        ],
        database_operations=[],
      ),
    ]
