# Generated by Django 5.2.4 on 2026-07-17 22:48

from django.db import migrations, models


def seed_whatsapp_service_client(apps, schema_editor):
    """
    CDC §7.2/§10.1 : le numéro WhatsApp du Service Client vit en base,
    éditable par l'administrateur général sans redéploiement — jamais dans
    settings.py. Valeur volontairement vide : aucun numéro réel n'est
    inventé ici, l'admin le renseigne via l'admin Django après migration
    (ParametreSystemeAdmin, apps/core/admin.py).
    """
    ParametreSysteme = apps.get_model('core', 'ParametreSysteme')
    ParametreSysteme.objects.get_or_create(
        cle='whatsapp_service_client',
        defaults={
            'valeur': '',
            'description': (
                "Numéro WhatsApp (format international, ex: 2376XXXXXXXX) "
                "utilisé par Repetiteur.lien_whatsapp pour rediriger vers le "
                "Service Client. À renseigner par l'administrateur général."
            ),
        },
    )


def revert_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametreSysteme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(db_index=True, max_length=100, unique=True)),
                ('valeur', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Paramètre système',
                'verbose_name_plural': 'Paramètres système',
                'db_table': 'yeki_parametre_systeme',
            },
        ),
        migrations.RunPython(seed_whatsapp_service_client, revert_noop),
    ]
