# Generated by Django 5.2.4 on 2026-07-18 01:31

from django.db import migrations, models

# P2.4 : valeurs initiales du modèle économique (CDC). Clés sans valeur
# ("valeur": "") : donnée réelle inconnue (numéro, code USSD...) — jamais
# inventée ici, à renseigner par l'administrateur général via l'admin
# Django (même traitement que whatsapp_service_client/url_base_frontend,
# déjà semées en P2.1 — non re-semées ici, get_or_create les laisse intactes).
PARAMETRES_P2_4 = [
    {
        "cle": "ussd_orange_money",
        "valeur": "",
        "type": "string",
        "description": "Code USSD Orange Money pour le paiement manuel (ex: #150#). À renseigner par l'administrateur général.",
    },
    {
        "cle": "ussd_mtn_momo",
        "valeur": "",
        "type": "string",
        "description": "Code USSD MTN Mobile Money pour le paiement manuel. À renseigner par l'administrateur général.",
    },
    {
        "cle": "numero_depot_orange",
        "valeur": "",
        "type": "string",
        "description": "Numéro Orange Money sur lequel les apprenants effectuent un dépôt manuel. À renseigner par l'administrateur général.",
    },
    {
        "cle": "numero_depot_mtn",
        "valeur": "",
        "type": "string",
        "description": "Numéro MTN Mobile Money sur lequel les apprenants effectuent un dépôt manuel. À renseigner par l'administrateur général.",
    },
    {
        "cle": "nom_affiche_depot",
        "valeur": "",
        "type": "string",
        "description": "Nom affiché au dépôt (ex: nom du titulaire du compte marchand). À renseigner par l'administrateur général.",
    },
    {
        "cle": "delai_validation_paiement_minutes",
        "valeur": "60",
        "type": "int",
        "description": "Délai annoncé à l'apprenant pour la validation d'un paiement manuel par le Service Client, en minutes.",
    },
    {
        "cle": "mode_paiement",
        "valeur": "manuel",
        "type": "string",
        "description": "Parcours de paiement actif : 'manuel', 'cinetpay', ou 'les_deux'. Décide du parcours à l'exécution, sans déploiement.",
    },
    {
        "cle": "usd_to_xaf",
        "valeur": "600",
        "type": "float",
        "description": "Taux de conversion USD → FCFA utilisé pour facturer les appels Yéki IA (tarification Claude en USD).",
    },
    {
        "cle": "modele_ia",
        "valeur": "claude-3-5-haiku-20241022",
        "type": "string",
        "description": "Nom du modèle Claude utilisé par Yéki IA — modifiable sans déploiement pour changer de modèle.",
    },
    {
        "cle": "commission_ia_pourcent",
        "valeur": "20",
        "type": "float",
        "description": "Commission Yéki sur chaque appel Yéki IA, en pourcentage du coût de base (remplace l'ancien montant fixe de 5 FCFA).",
    },
    {
        "cle": "solde_min_ia",
        "valeur": "20",
        "type": "int",
        "description": "Solde minimum du portefeuille Yéki requis pour utiliser Yéki IA, en FCFA.",
    },
    {
        "cle": "tarif_repetiteur_mensuel",
        "valeur": "7500",
        "type": "int",
        "description": "Tarif mensuel par défaut affiché pour un répétiteur, en FCFA (Repetiteur.tarif_mensuel).",
    },
    {
        "cle": "retrait_minimum",
        "valeur": "1000",
        "type": "int",
        "description": "Montant minimum autorisé pour une demande de retrait, en FCFA.",
    },
    {
        "cle": "part_yeki_olympiade",
        "valeur": "80",
        "type": "int",
        "description": "Part (%) du montant de participation à une olympiade reversée au compte Yéki (le reste va au cadre organisateur).",
    },
    {
        "cle": "part_yeki_formation",
        "valeur": "30",
        "type": "int",
        "description": "Part (%) du montant d'inscription à une formation reversée au compte Yéki. Non encore utilisée par un site d'appel (fonctionnalité pas encore implémentée) — semée pour usage futur.",
    },
]


def seed_parametres_p2_4(apps, schema_editor):
    ParametreSysteme = apps.get_model('core', 'ParametreSysteme')
    for parametre in PARAMETRES_P2_4:
        ParametreSysteme.objects.get_or_create(
            cle=parametre["cle"],
            defaults={
                "valeur": parametre["valeur"],
                "type": parametre["type"],
                "description": parametre["description"],
                "modifiable_par": "admin",
            },
        )


def revert_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seed_url_base_frontend'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametresysteme',
            name='modifiable_par',
            field=models.CharField(blank=True, default='admin', max_length=30),
        ),
        migrations.AddField(
            model_name='parametresysteme',
            name='type',
            field=models.CharField(choices=[('string', 'Texte'), ('int', 'Entier'), ('float', 'Décimal'), ('bool', 'Booléen')], default='string', max_length=10),
        ),
        migrations.RunPython(seed_parametres_p2_4, revert_noop),
    ]
