# Generated by Django 5.2.4 on 2026-07-24 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_parametresysteme_modifiable_par_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiqueactivite',
            name='action',
            field=models.CharField(choices=[('teacher_activated', 'Enseignant activé'), ('teacher_type_changed', 'Type enseignant modifié'), ('parcours_modified', 'Parcours modifié'), ('course_created', 'Cours créé'), ('course_modified', 'Cours modifié'), ('course_deleted', 'Cours supprimé'), ('teacher_assigned', 'Enseignant principal assigné'), ('teacher_changed', 'Enseignant principal changé'), ('secondary_added', 'Enseignant secondaire ajouté'), ('secondary_removed', 'Enseignant secondaire retiré'), ('module_created', 'Module créé'), ('module_modified', 'Module modifié'), ('module_deleted', 'Module supprimé'), ('lesson_created', 'Leçon créée'), ('lesson_modified', 'Leçon modifiée'), ('lesson_deleted', 'Leçon supprimée'), ('homework_created', 'Devoir créé'), ('homework_modified', 'Devoir modifié'), ('homework_graded', 'Devoir corrigé'), ('exercise_created', 'Exercice créé'), ('question_added', 'Question ajoutée'), ('olympiad_created', 'Olympiade créée'), ('olympiad_closed', 'Olympiade clôturée'), ('ranking_computed', 'Classement calculé'), ('department_created', 'Département créé'), ('cadre_assigned', 'Cadre assigné'), ('submission_graded', 'Soumission corrigée'), ('login', 'Connexion'), ('logout', 'Déconnexion'), ('payment_validated', 'Paiement manuel validé'), ('payment_rejected', 'Paiement manuel refusé'), ('ecart_montant_paiement', 'Écart de montant constaté')], max_length=50),
        ),
    ]
