# Generated by Django 5.2.4 on 2026-07-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_historiqueactivite_action'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appversion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='appversion',
            name='canal',
            field=models.CharField(choices=[('stable', 'Stable'), ('beta', 'Bêta'), ('alpha', 'Alpha')], default='stable', help_text='Canal de diffusion — un client ne reçoit que les versions de son canal.', max_length=20),
        ),
        migrations.AddField(
            model_name='appversion',
            name='checksum_sha256',
            field=models.CharField(blank=True, help_text="Empreinte SHA-256 (hex) du binaire publié — calculée manuellement avant publication (ex. `sha256sum app.apk`) et collée ici ; vérifiée côté client avant installation. Laissé vide = aucune vérification pour cette version (transition tant que les anciennes versions n'ont pas été rétro-remplies).", max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='appversion',
            unique_together={('platform', 'canal', 'version_code')},
        ),
    ]
