# Generated by Django 5.2.4 on 2026-07-17 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yeki', '0001_initial'),
    ]

    # SeparateDatabaseAndState : AppVersion/HistoriqueActivite déménagent
    # vers l'app "core" (voir apps/core/migrations/0001_initial.py) — on ne
    # fait que retirer ces modèles de l'état de l'app "yeki", les tables
    # yeki_appversion / yeki_historiqueactivite ne sont pas touchées
    # (database_operations=[]).
    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='AppVersion',
                ),
                migrations.DeleteModel(
                    name='HistoriqueActivite',
                ),
            ],
            database_operations=[],
        ),
    ]
