# Generated by Django 5.2.4 on 2026-07-17 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('yeki', '0002_delete_appversion_delete_historiqueactivite'),
    ]

    # SeparateDatabaseAndState : Profile/PasswordResetOTP déménagent vers
    # "accounts". Les AlterField ci-dessous ne mettent à jour QUE la
    # référence symbolique Django (to=) vers le nouvel app_label — la
    # colonne SQL sous-jacente (FK entière vers yeki_profile.id) ne change
    # pas du tout, donc aucune opération réelle sur la base
    # (database_operations=[]).
    operations = [
      migrations.SeparateDatabaseAndState(
        state_operations=[
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterField(
            model_name='olympiade',
            name='organisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olympiades_organisees', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='devoir',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoirs_crees', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='repetiteur',
            name='enseignant',
            field=models.ForeignKey(limit_choices_to={'user_type__in': ['enseignant', 'enseignant_secondaire']}, on_delete=django.db.models.deletion.CASCADE, related_name='fiches_repetiteur', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='parcours',
            name='admin',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'enseignant_admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcours_admin', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='lecon',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='enseignant_principal',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'enseignant_principal'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours_principal', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='departement',
            name='cadre',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'enseignant_cadre'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departements_cadre', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='enseignants',
            field=models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'enseignant'}, related_name='cours_secondaires', to='accounts.profile'),
        ),
        migrations.DeleteModel(
            name='PasswordResetOTP',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        ],
        database_operations=[],
      ),
    ]
