# Generated by Django 5.2.4 on 2026-07-17 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0001_initial'),
        ('yeki', '0003_remove_profile_user_alter_olympiade_organisateur_and_more'),
    ]

    # SeparateDatabaseAndState : les 9 modèles formation/ déménagent ; tous
    # les AlterField/RemoveField ci-dessous ne mettent à jour que les
    # références symboliques Django (to=) vers le nouvel app_label — aucune
    # colonne SQL ne change (les FK restent des entiers vers les mêmes
    # tables yeki_cours/yeki_departement/etc., db_table préservé).
    operations = [
      migrations.SeparateDatabaseAndState(
        state_operations=[
        migrations.AlterField(
            model_name='repetiteur',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repetiteurs', to='formation.cours'),
        ),
        migrations.AlterField(
            model_name='devoir',
            name='cours_lie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoirs', to='formation.cours'),
        ),
        migrations.RemoveField(
            model_name='module',
            name='cours',
        ),
        migrations.RemoveField(
            model_name='progressionlecon',
            name='cours',
        ),
        migrations.AlterField(
            model_name='exercice',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercices', to='formation.cours'),
        ),
        migrations.AlterField(
            model_name='yekiiapersonalite',
            name='cours_lie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ia_personnalites', to='formation.cours'),
        ),
        migrations.AlterField(
            model_name='yekiiachathistorique',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ia_chat_messages', to='formation.cours'),
        ),
        migrations.RemoveField(
            model_name='lecon',
            name='cours',
        ),
        migrations.AlterUniqueTogether(
            name='demandeaccesformation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='demandeaccesformation',
            name='apprenant',
        ),
        migrations.RemoveField(
            model_name='demandeaccesformation',
            name='departement',
        ),
        migrations.RemoveField(
            model_name='departement',
            name='apprenants_autorises',
        ),
        migrations.RemoveField(
            model_name='departement',
            name='cadre',
        ),
        migrations.RemoveField(
            model_name='departement',
            name='parcours',
        ),
        migrations.AlterField(
            model_name='rangapprenant',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rangs_apprenants', to='formation.departement'),
        ),
        migrations.RemoveField(
            model_name='lecon',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='lecon',
            name='module',
        ),
        migrations.RemoveField(
            model_name='progressionlecon',
            name='lecon',
        ),
        migrations.AlterField(
            model_name='exercice',
            name='lecon',
            field=models.ForeignKey(blank=True, help_text="Leçon à laquelle l'exercice est rattaché (optionnel)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercices', to='formation.lecon'),
        ),
        migrations.RemoveField(
            model_name='supplementcours',
            name='lecon',
        ),
        migrations.RemoveField(
            model_name='leconlike',
            name='lecon',
        ),
        migrations.AlterUniqueTogether(
            name='leconlike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='leconlike',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together=None,
        ),
        migrations.AlterField(
            model_name='exercice',
            name='module',
            field=models.ForeignKey(blank=True, help_text="Module auquel l'exercice est rattaché (optionnel)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercices', to='formation.module'),
        ),
        migrations.RemoveField(
            model_name='parcours',
            name='admin',
        ),
        migrations.AlterUniqueTogether(
            name='progressionlecon',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='progressionlecon',
            name='apprenant',
        ),
        migrations.DeleteModel(
            name='Cours',
        ),
        migrations.DeleteModel(
            name='DemandeAccesFormation',
        ),
        migrations.DeleteModel(
            name='Departement',
        ),
        migrations.DeleteModel(
            name='SupplementCours',
        ),
        migrations.DeleteModel(
            name='Lecon',
        ),
        migrations.DeleteModel(
            name='LeconLike',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.DeleteModel(
            name='Parcours',
        ),
        migrations.DeleteModel(
            name='ProgressionLecon',
        ),
        ],
        database_operations=[],
      ),
    ]
