# Generated by Django 5.2.4 on 2026-07-17 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yeki', '0005_remove_choixreponse_question_and_more'),
    ]

    # SeparateDatabaseAndState : forum/ déménage — état uniquement.
    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='questionforum',
                    name='auteur',
                ),
                migrations.RemoveField(
                    model_name='reponsequestion',
                    name='question',
                ),
                migrations.RemoveField(
                    model_name='reponseimage',
                    name='reponse',
                ),
                migrations.RemoveField(
                    model_name='reponsequestion',
                    name='auteur',
                ),
                migrations.DeleteModel(
                    name='LikeReponse',
                ),
                migrations.DeleteModel(
                    name='QuestionForum',
                ),
                migrations.DeleteModel(
                    name='ReponseImage',
                ),
                migrations.DeleteModel(
                    name='ReponseQuestion',
                ),
            ],
            database_operations=[],
        ),
    ]
