# Generated by Django 5.2.4 on 2026-07-17 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yeki', '0006_remove_questionforum_auteur_and_more'),
    ]

    # SeparateDatabaseAndState : paiement/ déménage — état uniquement.
    operations = [
      migrations.SeparateDatabaseAndState(
        state_operations=[
        migrations.RemoveField(
            model_name='abonnementpremium',
            name='paiement',
        ),
        migrations.RemoveField(
            model_name='abonnementpremium',
            name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='cinetpaytransaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='olympiade_liee',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='utilisateur',
        ),
        migrations.AlterUniqueTogether(
            name='paiementolympiade',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='paiementolympiade',
            name='apprenant',
        ),
        migrations.RemoveField(
            model_name='paiementolympiade',
            name='olympiade',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='wallet',
        ),
        migrations.DeleteModel(
            name='YekiCompteIA',
        ),
        migrations.RemoveField(
            model_name='yekiwallet',
            name='utilisateur',
        ),
        migrations.DeleteModel(
            name='AbonnementPremium',
        ),
        migrations.DeleteModel(
            name='CinetPayTransaction',
        ),
        migrations.DeleteModel(
            name='Paiement',
        ),
        migrations.DeleteModel(
            name='PaiementOlympiade',
        ),
        migrations.DeleteModel(
            name='WalletTransaction',
        ),
        migrations.DeleteModel(
            name='YekiWallet',
        ),
        ],
        database_operations=[],
      ),
    ]
