# Generated by Django 5.2.4 on 2026-07-17 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yeki', '0007_remove_abonnementpremium_paiement_and_more'),
    ]

    # SeparateDatabaseAndState : ia/ déménage — état uniquement.
    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='yekiiapersonalite',
                    name='cours_lie',
                ),
                migrations.DeleteModel(
                    name='YekiIAChatHistorique',
                ),
                migrations.DeleteModel(
                    name='YekiIAPersonalite',
                ),
            ],
            database_operations=[],
        ),
    ]
