# Generated by Django 5.2.4 on 2026-07-17 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yeki', '0008_remove_yekiiapersonalite_cours_lie_and_more'),
    ]

    # SeparateDatabaseAndState : notifications/ déménage — état uniquement.
    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Notification',
                ),
            ],
            database_operations=[],
        ),
    ]
