# Generated by Django 5.2.4 on 2026-07-17 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yeki', '0009_delete_notification'),
    ]

    # SeparateDatabaseAndState : repetiteurs/ déménage — état uniquement.
    # Dernière app du plan : yeki/models.py devient un pur ré-export après
    # cette migration (voir docs/MIGRATIONS_APPS.md).
    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Repetiteur',
                ),
            ],
            database_operations=[],
        ),
    ]
