# Generated by Django 5.2.4 on 2026-07-17 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # SeparateDatabaseAndState : les 9 tables existent déjà (créées par
    # yeki.0001_initial) — état uniquement, aucune opération réelle.
    operations = [
      migrations.SeparateDatabaseAndState(
        state_operations=[
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('niveau_formation', models.CharField(blank=True, choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé')], default='debutant', help_text='Niveau de la formation (pour les formations métier)', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description détaillée')),
                ('image', models.ImageField(blank=True, help_text='Image de couverture du département', null=True, upload_to='departements/images/')),
                ('couleur', models.CharField(default='#2884A0', help_text='Couleur principale #RRGGBB', max_length=7)),
                ('est_actif', models.BooleanField(default=True, help_text='Visible aux apprenants si True')),
                ('prix', models.PositiveIntegerField(default=0, help_text="Prix d'accès en FCFA (0 = gratuit)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('periode', models.PositiveIntegerField(default=6, help_text="Durée d'une période de classement en mois (1, 3, 6, 12)")),
                ('date_debut_periode', models.DateTimeField(auto_now_add=True, help_text='Début de la période de classement en cours')),
                ('date_fin_periode', models.DateTimeField(blank=True, help_text='Calculée = date_debut_periode + periode mois. Recalculée à chaque réinitialisation.', null=True)),
                ('est_prepa_concours', models.BooleanField(default=False, help_text='True = ce département est un concours à préparer')),
                ('nom_concours', models.CharField(blank=True, help_text='Nom officiel du concours (ex: ENS, Polytechnique, BEPC…)', max_length=255)),
                ('organisme_concours', models.CharField(blank=True, help_text='Organisme/institution organisateur', max_length=255)),
                ('date_limite_inscription', models.DateField(blank=True, help_text="Date limite d'inscription au concours", null=True)),
                ('date_examen', models.DateField(blank=True, help_text="Date prévue de l'examen / concours", null=True)),
                ('arrete_ministeriel', models.CharField(blank=True, help_text="Référence de l'arrêté ministériel d'organisation", max_length=255)),
                ('niveaux_cibles', models.CharField(blank=True, help_text='Niveaux ciblés ex: Terminale, Licence 3, Master 1', max_length=255)),
                ('places_disponibles', models.PositiveIntegerField(blank=True, help_text='Nombre de places au concours (null = non précisé)', null=True)),
                ('debouches', models.TextField(blank=True, help_text='Débouchés après réussite du concours')),
                ('acces_restreint', models.BooleanField(default=False, help_text='Accès limité aux apprenants sélectionnés')),
                ('est_formation_metier', models.BooleanField(default=False, help_text='True = formation orientée compétences métier')),
                ('est_formation_classique', models.BooleanField(default=False, help_text='True = formation académique classique (université, grande école…)')),
                ('duree_formation', models.CharField(blank=True, help_text='Ex: 6 mois, 2 ans, 200 heures…', max_length=100)),
                ('mode', models.CharField(blank=True, choices=[('presentiel', 'Présentiel'), ('distance', 'À distance'), ('hybride', 'Hybride')], default='hybride', help_text='Mode de diffusion', max_length=20)),
                ('certificat_delivre', models.CharField(blank=True, help_text='Certificat / diplôme délivré à la fin', max_length=255)),
                ('prerequis', models.TextField(blank=True, help_text='Prérequis pour intégrer la formation')),
                ('objectifs', models.TextField(blank=True, help_text='Objectifs pédagogiques de la formation')),
                ('domaine', models.CharField(blank=True, help_text='Domaine professionnel (Informatique, Gestion, Santé…)', max_length=255)),
                ('ville', models.CharField(blank=True, help_text='Ville principale où se déroule la formation', max_length=100)),
                ('est_certifiante', models.BooleanField(default=False, help_text='True si la formation délivre un certificat reconnu')),
                ('niveaux_accessibles', models.TextField(blank=True, help_text="Liste des niveaux séparés par des virgules (ex: 'Terminale,Licence 1,Licence 2')")),
                ('prix_presentiel', models.PositiveIntegerField(default=0, help_text='Prix en présentiel (supplément) en FCFA. Le prix total = prix (en ligne) + prix_presentiel')),
                ('prix_mensuel', models.PositiveIntegerField(default=0, help_text='Prix abonnement mensuel en ligne (FCFA)')),
                ('prix_annuel', models.PositiveIntegerField(default=0, help_text='Prix abonnement annuel en ligne (FCFA)')),
                ('prix_presentiel_mensuel', models.PositiveIntegerField(blank=True, default=0, help_text='Supplément présentiel mensuel, facultatif (FCFA)')),
                ('prix_presentiel_annuel', models.PositiveIntegerField(blank=True, default=0, help_text='Supplément présentiel annuel, facultatif (FCFA)')),
                ('apprenants_autorises', models.ManyToManyField(blank=True, help_text='Apprenants autorisés à accéder à cette formation (si acces_restreint=True)', related_name='formations_autorisees', to=settings.AUTH_USER_MODEL)),
                ('cadre', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'enseignant_cadre'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departements_cadre', to='accounts.profile')),
            ],
            options={
                'db_table': 'yeki_departement',
                'ordering': ['parcours', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('niveau', models.CharField(max_length=200)),
                ('matiere', models.CharField(blank=True, max_length=255)),
                ('concours', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nb_apprenants', models.PositiveIntegerField(default=0)),
                ('description_brief', models.CharField(blank=True, help_text='Description courte du cours', max_length=255, null=True)),
                ('color_code', models.CharField(choices=[('#7C3AED', 'Violet Électrique'), ('#10B981', 'Émeraude'), ('#EA580C', 'Orange Brûlé'), ('#DB2777', 'Rose Fuchsia'), ('#2563EB', 'Bleu Roi'), ('#CA8A04', 'Or Ambré'), ('#0D9488', 'Sarcelle'), ('#DC2626', 'Rouge Corail'), ('#9333EA', 'Pourpre'), ('#059669', 'Vert Jade'), ('#EC4899', 'Magenta'), ('#0284C7', 'Cyan Profond')], default='#2563EB', help_text="Couleur d'accentuation du cours, choisie parmi la palette YÉKI officielle (voir COURSE_COLOR_PALETTE).", max_length=7)),
                ('icon_name', models.CharField(default='school', help_text='Nom de l’icône Flutter (MaterialIcons)', max_length=50)),
                ('nb_devoirs', models.PositiveIntegerField(default=0)),
                ('nb_lecons', models.PositiveIntegerField(default=0)),
                ('niveau_professionnel', models.CharField(blank=True, choices=[('amateur', 'Amateur'), ('expert', 'Expert'), ('professionnel', 'Professionnel')], help_text='Niveau professionnel visé (formations métier uniquement)', max_length=20, null=True)),
                ('enseignant_principal', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'enseignant_principal'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours_principal', to='accounts.profile')),
                ('enseignants', models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'enseignant'}, related_name='cours_secondaires', to='accounts.profile')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='formation.departement')),
            ],
            options={
                'db_table': 'yeki_cours',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.CharField(default='', max_length=200)),
                ('ordre', models.PositiveIntegerField(help_text="Ordre défini par l'enseignant principal")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='formation.cours')),
            ],
            options={
                'db_table': 'yeki_module',
                'ordering': ['ordre'],
                'unique_together': {('cours', 'ordre')},
            },
        ),
        migrations.CreateModel(
            name='Lecon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('fichier_pdf', models.FileField(blank=True, help_text='PDF du cours', null=True, upload_to='lecons/pdf/')),
                ('video', models.FileField(blank=True, null=True, upload_to='lecons/video/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecons', to='formation.cours')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.profile')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecons', to='formation.module')),
            ],
            options={
                'db_table': 'yeki_lecon',
            },
        ),
        migrations.CreateModel(
            name='Parcours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_parcours', models.CharField(choices=[('cursus', 'Cursus scolaire / universitaire'), ('prepa', 'Prépa Concours'), ('formation', 'Formations professionnelles'), ('autre', 'Autre')], default='autre', help_text="Nature du parcours pour guider l'affichage", max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'enseignant_admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcours_admin', to='accounts.profile')),
            ],
            options={
                'db_table': 'yeki_parcours',
            },
        ),
        migrations.AddField(
            model_name='departement',
            name='parcours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departements', to='formation.parcours'),
        ),
        migrations.CreateModel(
            name='SupplementCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type_contenu', models.CharField(choices=[('lien', 'Lien'), ('pdf', 'PDF'), ('video', 'Vidéo'), ('ppt', 'PowerPoint')], max_length=20)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='supplements/')),
                ('url', models.URLField(blank=True, null=True)),
                ('ordre', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lecon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplements', to='formation.lecon')),
            ],
            options={
                'verbose_name': 'Supplément de cours',
                'db_table': 'yeki_supplementcours',
                'ordering': ['ordre', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='DemandeAccesFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='en_attente', max_length=20)),
                ('message', models.TextField(blank=True, help_text="Message de l'apprenant")),
                ('reponse_cadre', models.TextField(blank=True, help_text='Réponse du cadre')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('traite_le', models.DateTimeField(blank=True, null=True)),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_acces', to=settings.AUTH_USER_MODEL)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_acces', to='formation.departement')),
            ],
            options={
                'db_table': 'yeki_demandeaccesformation',
                'ordering': ['-cree_le'],
                'unique_together': {('apprenant', 'departement')},
            },
        ),
        migrations.CreateModel(
            name='LeconLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lecon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='formation.lecon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecon_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'yeki_leconlike',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'lecon')},
            },
        ),
        migrations.CreateModel(
            name='ProgressionLecon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pourcentage', models.PositiveSmallIntegerField(default=0)),
                ('derniere_vue', models.DateTimeField(auto_now=True)),
                ('terminee', models.BooleanField(default=False)),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to=settings.AUTH_USER_MODEL)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='formation.cours')),
                ('lecon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='formation.lecon')),
            ],
            options={
                'db_table': 'yeki_progressionlecon',
                'ordering': ['-derniere_vue'],
                'unique_together': {('apprenant', 'lecon')},
            },
        ),
        ],
        database_operations=[],
      ),
    ]
