# Generated by Django 5.2.4 on 2026-07-18 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_is_repetiteur_alter_profile_user_type'),
        ('formation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriquePrixDepartement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champ', models.CharField(help_text="'prix' ou 'prix_presentiel'", max_length=50)),
                ('ancienne_valeur', models.PositiveIntegerField()),
                ('nouvelle_valeur', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_prix', to='formation.departement')),
                ('par_qui', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.profile')),
            ],
            options={
                'verbose_name': 'Historique de prix (département)',
                'db_table': 'yeki_historique_prix_departement',
                'ordering': ['-date'],
            },
        ),
    ]
