# Generated by Django 5.2.4 on 2026-07-29 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0002_historiqueprixdepartement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departement',
            name='niveau_formation',
            field=models.CharField(blank=True, default='debutant', help_text="Niveau de la formation (pour les formations métier) — liste fermée mais administrable sans redéploiement, voir `ParametreSysteme` clé `niveaux_formation_disponibles` (services.niveaux_formation_disponibles) plutôt qu'un `choices=` figé ici (P11.6).", max_length=20),
        ),
    ]
