# Generated by Django 5.2.4 on 2026-08-09 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formation", "0004_supplementcours_cours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cours",
            name="color_code",
            field=models.CharField(
                choices=[
                    ("#2E7CAD", "Azur"),
                    ("#5F6BD4", "Bleu"),
                    ("#8A5CD4", "Indigo"),
                    ("#BB39CB", "Violet"),
                    ("#CB3B92", "Magenta"),
                    ("#CD4453", "Rose"),
                    ("#AE612E", "Orange"),
                    ("#817622", "Ambre"),
                    ("#5C8022", "Lime"),
                    ("#2E8624", "Vert"),
                    ("#23854A", "Émeraude"),
                    ("#238278", "Turquoise"),
                ],
                default="#2E7CAD",
                help_text="Couleur d'accentuation du cours, choisie parmi la palette YÉKI officielle (voir COURSE_COLOR_PALETTE).",
                max_length=7,
            ),
        ),
    ]
