"""
Settings communs YÉKI backend — partagés par development.py et production.py.

Generated by 'django-admin startproject' using Django 5.1.4, puis restructuré
en apps/ + config/ (voir CDC_BACKEND §3.1). Aucune app métier n'a été
déplacée : `yeki/` continue de porter tout le code existant.
"""

import os
import environ
from pathlib import Path


# config/settings/base.py -> config/settings/ -> config/ -> racine du projet
# (là où vivent manage.py et .env).
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# ── Variables d'environnement ───────────────────────────────────────────────
# Toutes les valeurs sensibles (clé secrète Django, identifiants email, clés
# API de paiement, identifiants base de données en production) sont lues
# depuis l'environnement, jamais codées en dur.
# En local : copier .env.example vers .env à la racine du projet (à côté de
# manage.py) et renseigner les valeurs réelles (jamais commité, voir .gitignore).
# En production (PythonAnywhere) : définir les variables directement dans la
# configuration de l'environnement du serveur ; le fichier .env n'est alors
# pas nécessaire (read_env() ignore silencieusement son absence).
env = environ.Env()
environ.Env.read_env(str(BASE_DIR / ".env"))


# SECURITY WARNING: keep the secret key used in production secret!
# Volontairement SANS valeur par défaut : si SECRET_KEY est absente de
# l'environnement, le démarrage doit échouer plutôt que de tourner avec une
# clé de test ou (pire) une clé devinable.
SECRET_KEY = env("SECRET_KEY")
DEFAULT_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"

# DEBUG, ALLOWED_HOSTS et DATABASES sont volontairement définis dans
# development.py / production.py, pas ici : ce sont les seuls réglages qui
# doivent réellement différer par environnement.

CORS_ALLOWED_ORIGINS = [
    "https://yeki.pythonanywhere.com",
    "http://localhost:53299",
    "https://yeki-84b1a.web.app",
]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "drf_spectacular",
    "corsheaders",
    "yeki.apps.YekiConfig",
    # ── Nouvelle structure modulaire (CDC_BACKEND §3.1) ────────────────────
    # Squelette uniquement pour l'instant : aucun modèle/vue n'a encore été
    # déplacé depuis yeki/. Ces apps sont vides.
    "apps.core.apps.CoreConfig",
    "apps.accounts.apps.AccountsConfig",
    "apps.formation.apps.FormationConfig",
    "apps.evaluation.apps.EvaluationConfig",
    "apps.forum.apps.ForumConfig",
    "apps.paiement.apps.PaiementConfig",
    "apps.ia.apps.IaConfig",
    "apps.notifications.apps.NotificationsConfig",
    "apps.repetiteurs.apps.RepetiteursConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # CorsMiddleware doit être le plus haut possible et impérativement avant
    # CommonMiddleware (exigence django-cors-headers) : sinon les réponses
    # court-circuitées par les middlewares au-dessus (redirections, erreurs)
    # ne reçoivent jamais les en-têtes CORS → bugs CORS intermittents en web.
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    # LocaleMiddleware : après SessionMiddleware, avant CommonMiddleware
    # (position exigée par Django). Interface en français, voir LANGUAGE_CODE.
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        # API fermée par défaut : toute vue future sans permission_classes
        # explicite exige désormais une authentification, plutôt que d'être
        # publique en écriture sans que personne ne le remarque. Les rares
        # endpoints réellement publics (login, register, mot de passe oublié,
        # niveaux par département, landing, version d'app, webhook CinetPay)
        # déclarent AllowAny explicitement sur leur propre vue.
        "rest_framework.permissions.IsAuthenticated",
    ],
    # ── Fondations couche API (voir docs/API_FOUNDATIONS.md) ────────────────
    # Enveloppe d'erreur uniforme {"error": {code, message, fields, request_id}}
    # — `fields` est ce qui permet à YkForm (frontend) d'afficher l'erreur
    # sous le bon champ plutôt qu'un SnackBar générique.
    "EXCEPTION_HANDLER": "apps.core.exceptions.custom_exception_handler",
    "DEFAULT_PAGINATION_CLASS": "apps.core.pagination.YekiPageNumberPagination",
    "PAGE_SIZE": 20,
    # ScopedRateThrottle est sans effet sur une vue qui ne définit pas
    # `throttle_scope` : l'inclure globalement ici permet à login/otp/ia/
    # paiement de déclarer juste `throttle_scope = '...'` sans avoir à
    # surcharger `throttle_classes` vue par vue.
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
        "rest_framework.throttling.ScopedRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "30/min",
        "user": "120/min",
        "login": "5/min",  # anti brute-force connexion
        "ia": "10/min",  # Yéki IA — facturée au token
        "paiement": "10/min",  # anti-spam de demandes de paiement
        "otp": "3/10min",  # anti-abus de l'envoi d'OTP par email
    },
    # ── Documentation API (P1.6, voir docs/API_FOUNDATIONS.md) ─────────────
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

# drf-spectacular : /api/schema/ (OpenAPI brut) + /api/docs/ (Swagger UI),
# voir config/urls.py. SERVE_INCLUDE_SCHEMA=False évite que le schéma
# s'auto-référence dans sa propre documentation.
SPECTACULAR_SETTINGS = {
    "TITLE": "API YÉKI",
    "DESCRIPTION": (
        "Contrat backend↔frontend de la plateforme e-learning YÉKI. "
        "Enveloppe d'erreur, pagination et throttling communs décrits dans "
        "docs/API_FOUNDATIONS.md."
    ),
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}


ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


WSGI_APPLICATION = "config.wsgi.application"


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/
# Réglage global (pas seulement production) : interface en français, fuseau
# Africa/Douala pour tout l'environnement — un dev qui tourne en UTC/anglais
# pendant que la prod tourne en Africa/Douala/français est une source
# classique de bugs d'affichage de dates.

LANGUAGE_CODE = "fr-fr"

TIME_ZONE = "Africa/Douala"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ── Cache (P2.4) ─────────────────────────────────────────────────────────────
# Cache mémoire (par process) pour ParametreSysteme.get() — voir
# apps/core/signals.py pour l'invalidation à l'écriture. LocMemCache est déjà
# le défaut implicite de Django sans configuration ; explicité ici pour
# documenter l'intention (« cache mémoire », voir docs/API_FOUNDATIONS.md).
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
    }
}


# ── Email (Gmail SMTP) ──────────────────────────────────────────────────────
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = env("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")  # mot de passe d'application Gmail
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# ── CinetPay (paiement) ──────────────────────────────────────────────────────
# Volontairement SANS valeur par défaut : une clé de paiement absente ne doit
# jamais retomber silencieusement sur une clé active codée en dur.
CINETPAY_API_KEY = env("CINETPAY_API_KEY")
CINETPAY_SITE_ID = env("CINETPAY_SITE_ID")
