# Generated by Django 5.2.4 on 2026-07-17 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # SeparateDatabaseAndState : les 2 tables existent déjà (créées par
    # yeki.0001_initial) — état uniquement, aucune opération réelle.
    operations = [
      migrations.SeparateDatabaseAndState(
        state_operations=[
        migrations.CreateModel(
            name='YekiIAChatHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Apprenant'), ('assistant', 'Yeki IA')], max_length=10)),
                ('contenu', models.TextField()),
                ('source', models.CharField(blank=True, help_text='lecon | exercice | devoir | libre', max_length=20)),
                ('source_id', models.IntegerField(blank=True, null=True)),
                ('source_titre', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ia_chat_images/')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('tokens', models.PositiveIntegerField(default=0)),
                ('tokens_input', models.PositiveIntegerField(default=0, help_text='Nombre de tokens en entrée')),
                ('tokens_output', models.PositiveIntegerField(default=0, help_text='Nombre de tokens en sortie')),
                ('audio', models.FileField(blank=True, help_text='Fichier audio joint à la question', null=True, upload_to='ia_chat_audios/')),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ia_chat_historique', to=settings.AUTH_USER_MODEL)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ia_chat_messages', to='formation.cours')),
            ],
            options={
                'verbose_name': 'Message IA Chat',
                'db_table': 'yeki_yekiiachathistorique',
                'ordering': ['cree_le'],
            },
        ),
        migrations.CreateModel(
            name='YekiIAPersonalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('contexte', models.CharField(choices=[('cursus_niveau', 'Niveau dans le cursus'), ('parcours', 'Parcours complet (Prépa Concours, Formations…)'), ('cours', 'Cours spécifique'), ('olympiade', 'Olympiade')], max_length=20)),
                ('style', models.CharField(choices=[('pedagogique', 'Pédagogique (explications détaillées)'), ('socratique', 'Socratique (questions pour guider)'), ('direct', 'Direct (réponses concises)'), ('encourageant', 'Encourageant (bienveillant et motivant)'), ('academique', 'Académique (rigoureux et formel)'), ('professionnel', 'Professionnel (orienté compétences)')], default='pedagogique', max_length=20)),
                ('niveau_difficulte', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé')], default='intermediaire', max_length=15)),
                ('nom_parcours', models.CharField(blank=True, help_text="Nom du Parcours (ex: 'Prépa Concours', 'Formations')", max_length=100)),
                ('niveau_cursus', models.CharField(blank=True, help_text='Ex: Terminale, 3ème…', max_length=50)),
                ('prompt_systeme', models.TextField(blank=True)),
                ('contexte_cours_cache', models.TextField(blank=True)),
                ('cache_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cours_lie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ia_personnalites', to='formation.cours')),
            ],
            options={
                'verbose_name': 'Personnalité IA',
                'verbose_name_plural': 'Personnalités IA',
                'db_table': 'yeki_yekiiapersonalite',
            },
        ),
        ],
        database_operations=[],
      ),
    ]
