"""
Django settings for yeki_backend project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import environ
from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ── Variables d'environnement ───────────────────────────────────────────────
# Toutes les valeurs sensibles (clé secrète Django, identifiants email, clés
# API de paiement) sont lues depuis l'environnement, jamais codées en dur.
# En local : copier .env.example vers .env à la racine du projet (à côté de
# manage.py) et renseigner les valeurs réelles (jamais commité, voir .gitignore).
# En production (PythonAnywhere) : définir les variables directement dans la
# configuration de l'environnement du serveur ; le fichier .env n'est alors
# pas nécessaire (read_env() ignore silencieusement son absence).
env = environ.Env()
environ.Env.read_env(str(BASE_DIR / '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Volontairement SANS valeur par défaut : si SECRET_KEY est absente de
# l'environnement, le démarrage doit échouer plutôt que de tourner avec une
# clé de test ou (pire) une clé devinable.
SECRET_KEY = env('SECRET_KEY')
DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['yeki.pythonanywhere.com']

CORS_ALLOWED_ORIGINS = [
    "https://yeki.pythonanywhere.com",
    "http://localhost:53299",
    'https://yeki-84b1a.web.app',
]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'yeki.apps.YekiConfig',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # CorsMiddleware doit être le plus haut possible et impérativement avant
    # CommonMiddleware (exigence django-cors-headers) : sinon les réponses
    # court-circuitées par les middlewares au-dessus (redirections, erreurs)
    # ne reçoivent jamais les en-têtes CORS → bugs CORS intermittents en web.
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    # LocaleMiddleware : après SessionMiddleware, avant CommonMiddleware
    # (position exigée par Django). Interface en français, voir LANGUAGE_CODE.
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        # API fermée par défaut : toute vue future sans permission_classes
        # explicite exige désormais une authentification, plutôt que d'être
        # publique en écriture sans que personne ne le remarque. Les rares
        # endpoints réellement publics (login, register, mot de passe oublié,
        # niveaux par département, landing, version d'app, webhook CinetPay)
        # déclarent AllowAny explicitement sur leur propre vue.
        'rest_framework.permissions.IsAuthenticated',
    ],
}



ROOT_URLCONF = "yeki_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


WSGI_APPLICATION = "yeki_backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "fr"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ── Email (Gmail SMTP) ──────────────────────────────────────────────────────
EMAIL_BACKEND       = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST          = 'smtp.gmail.com'
EMAIL_PORT          = 587
EMAIL_USE_TLS       = True
EMAIL_HOST_USER     = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')      # mot de passe d'application Gmail
DEFAULT_FROM_EMAIL  = EMAIL_HOST_USER


# ── CinetPay (paiement) ──────────────────────────────────────────────────────
# Volontairement SANS valeur par défaut : une clé de paiement absente ne doit
# jamais retomber silencieusement sur une clé active codée en dur.
CINETPAY_API_KEY = env('CINETPAY_API_KEY')
CINETPAY_SITE_ID = env('CINETPAY_SITE_ID')
