# Generated by Django 5.2.4 on 2026-07-17 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # SeparateDatabaseAndState : les 4 tables existent déjà (créées par
    # yeki.0001_initial) — état uniquement, aucune opération réelle.
    operations = [
      migrations.SeparateDatabaseAndState(
        state_operations=[
        migrations.CreateModel(
            name='QuestionForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(blank=True, null=True)),
                ('source', models.CharField(choices=[('lecon', 'Leçon'), ('exercice', 'Exercice'), ('devoir', 'Devoir'), ('libre', 'Question libre')], default='libre', max_length=20)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('lecon_id', models.IntegerField(blank=True, null=True)),
                ('lecon_titre', models.CharField(blank=True, max_length=255)),
                ('cours_id', models.IntegerField(blank=True, null=True)),
                ('cours_titre', models.CharField(blank=True, max_length=255)),
                ('exercice_id', models.IntegerField(blank=True, null=True)),
                ('exercice_titre', models.CharField(blank=True, max_length=255)),
                ('devoir_id', models.IntegerField(blank=True, null=True)),
                ('devoir_titre', models.CharField(blank=True, max_length=255)),
                ('est_resolue', models.BooleanField(default=False)),
                ('nb_vues', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, help_text='Image jointe à la question', null=True, upload_to='forum/questions/images/')),
                ('audio', models.FileField(blank=True, help_text='Fichier audio joint à la question', null=True, upload_to='forum/questions/audios/')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_forum', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'yeki_questionforum',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='ReponseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('est_solution', models.BooleanField(default=False)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_forum', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='forum.questionforum')),
            ],
            options={
                'db_table': 'yeki_reponsequestion',
                'ordering': ['cree_le'],
            },
        ),
        migrations.CreateModel(
            name='ReponseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='forum/reponses/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='forum.reponsequestion')),
            ],
            options={
                'db_table': 'yeki_reponseimage',
            },
        ),
        migrations.CreateModel(
            name='LikeReponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='forum.reponsequestion')),
            ],
            options={
                'db_table': 'yeki_likereponse',
                'unique_together': {('reponse', 'utilisateur')},
            },
        ),
        ],
        database_operations=[],
      ),
    ]
