# Generated by Django 5.2.4 on 2026-07-17 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # SeparateDatabaseAndState : la table existe déjà (créée par
    # yeki.0001_initial) — état uniquement, aucune opération réelle.
    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Notification',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('type', models.CharField(choices=[('devoir', 'Devoir'), ('correction', 'Correction'), ('olympiade', 'Olympiade'), ('rappel', 'Rappel'), ('classement', 'Classement'), ('forum', 'Forum'), ('system', 'Système')], default='system', max_length=20)),
                        ('titre', models.CharField(max_length=255)),
                        ('contenu', models.TextField()),
                        ('est_lue', models.BooleanField(default=False)),
                        ('cree_le', models.DateTimeField(auto_now_add=True)),
                        ('objet_id', models.PositiveIntegerField(blank=True, null=True)),
                        ('objet_type', models.CharField(blank=True, max_length=50)),
                        ('action_url', models.CharField(blank=True, help_text='URL de redirection', max_length=500)),
                        ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'Notification',
                        'verbose_name_plural': 'Notifications',
                        'db_table': 'yeki_notification',
                        'ordering': ['-cree_le'],
                        'indexes': [models.Index(fields=['utilisateur', 'est_lue'], name='yeki_notifi_utilisa_c62f5c_idx'), models.Index(fields=['utilisateur', 'cree_le'], name='yeki_notifi_utilisa_216570_idx')],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
