# Generated by Django 5.2.4 on 2026-07-24 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_devicetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('devoir', 'Devoir'), ('correction', 'Correction'), ('olympiade', 'Olympiade'), ('rappel', 'Rappel'), ('classement', 'Classement'), ('forum', 'Forum'), ('system', 'Système'), ('paiement', 'Paiement')], default='system', max_length=20),
        ),
    ]
