# Generated by Django 5.2.4 on 2026-07-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_rename_action_url_to_action_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action_route',
            field=models.CharField(blank=True, help_text='Chemin de redirection (go_router)', max_length=500),
        ),
    ]
